Repository sprint6-team12/arbaba-40owners, pull requests merged in 2024-06, with the labels that each got.

#5 ✨feat: Modal Component 추가
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalCustom.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/Modal/ModalsWrapper.tsx
  src/hooks/useModal.ts
  src/pages/_app.tsx
  src/recoil/atoms/ModalAtom.ts
  src/styles/globals.css
Labels: :sparkles: FEATURE

#6 ✨feat: Popup Component 추가
  .husky/_/pre-commit
  .husky/_/pre-push
  README.md
  package.json
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupsWrapper.tsx
  src/hooks/usePopup.ts
  src/pages/_app.tsx
  src/recoil/atoms/PopupAtom.ts
  tailwind.config.ts
Labels: :sparkles: FEATURE

#12 ✨feat: DD 4 gnb footer
  package-lock.json
  src/components/Footer/footer.tsx
  src/components/Gnb/Gnb.tsx
  src/components/Gnb/GnbButton.tsx
  src/components/Gnb/GnbUiButton.tsx
  src/components/Gnb/NotificationButton.tsx
  src/components/Gnb/SearchBar.tsx
  tailwind.config.ts
Labels: :sparkles: FEATURE

#14 ✨feat: Table 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Table/EmployeeTable.tsx
  src/components/Table/EmployerTable.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: :sparkles: FEATURE

#19 ✨feat: Badge 컴포넌트 추가
  src/components/Badge/FilterBadge.tsx
  src/components/Badge/RateBadge.tsx
  src/components/Badge/StatusBadge.tsx
  src/constants/statusMap.ts
  src/hooks/useColorByRate.ts
Labels: :sparkles: FEATURE

#20 ✨feat: Pagination 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Pagenation/Pagenation.tsx
Labels: :sparkles: FEATURE

#25 🐛 fix: Image optimization 누락 파일 및 오타 수정
  public/images/icon-arrow-up-bold.svg
  src/utils/Icons.tsx
Labels: :bug: FIX

#18 ✨feat: Dropdown Component 추가
  src/components/Dropdown/Dropdown.tsx
  src/components/Filter/Filter.tsx
  src/constants/DataLocations.ts
Labels: :sparkles: FEATURE

#23 ✨feat: LoginSignUp 페이지 추가
  next.config.mjs
  public/images/icon-checked.svg
  src/components/FormGroup/FormGroup.tsx
  src/components/LoginSignUp/InputComponent.tsx
  src/components/LoginSignUp/LoginSignUp.tsx
  src/components/LoginSignUp/MemberTypeButton.tsx
  src/components/LoginSignUp/MemberTypeToggle.tsx
  src/components/LoginSignUp/SignInForm.tsx
  src/components/LoginSignUp/SignUpForm.tsx
  src/components/LoginSignUp/ToggleContainer.tsx
  src/constants/validation.ts
  src/hooks/useAuth.ts
  src/recoil/atoms/AuthAtom.ts
  src/utils/Icons.tsx
  src/utils/api/ApiError.ts
  src/utils/api/authenticationAPI.tsx
  src/utils/api/axiosInstance.tsx
  src/utils/api/userAPI.tsx
  src/utils/validation.ts
  tailwind.config.ts
Labels: :sparkles: FEATURE

#29 fix: rate-badge 스타일 동적 추가 오류 해결
  src/components/Badge/RateBadge.tsx
  src/components/LoginSignUp/ToggleContainer.tsx
  src/hooks/useColorByRate.ts
  src/utils/api/authenticationAPI.tsx
  tailwind.config.ts
Labels: :bug: FIX

#28 ♻️refactor: Post컴포넌트 합성컴포넌트 방식으로 리팩토링
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
  src/components/Post/PostImage.tsx
  src/components/Post/PostInformation.tsx
  src/components/Post/PostPrice.tsx
  src/lib/utils/FormatUtils.ts
  src/types/Notice.d.ts
  src/types/Shop.d.ts
  src/types/Status.d.ts
Labels: :recycle: REFACTOR

#24 ✨feat: api 로직 구성
  src/pages/api/hello.ts
  src/utils/api/ApiError.ts
  src/utils/api/alertAPI.ts
  src/utils/api/applicationAPI.ts
  src/utils/api/authenticationAPI.ts
  src/utils/api/axiosInstance.ts
  src/utils/api/imageAPI.ts
  src/utils/api/noticeAPI.ts
  src/utils/api/shopAPI.ts
  src/utils/api/test.tsx
  src/utils/api/userAPI.ts
Labels: :sparkles: FEATURE

#33 🐛fix: placeholder오류 수정
  src/components/Dropdown/Dropdown.tsx
Labels: :bug: FIX

#31 ✨ feat: add notice page (공고등록페이지, 1차)
  src/components/ShopDetail/ShopNoData.tsx
  src/components/pageComponents/AddNotice/AddNoticeInput.tsx
  src/constants/errorMessage.ts
  src/lib/utils/InputValidation.ts
  src/pages/shops/[shop_id]/notices/index.tsx
Labels: :sparkles: FEATURE

#34 🐛fix: hotfix/Post 컴포넌트 데이터 타입 재설정
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
  src/types/Notice.d.ts
  src/types/Shop.d.ts
Labels: :bug: FIX

#36 feat: 공고리스트 페이지 추가
  next.config.mjs
  src/components/Badge/RateBadge.tsx
  src/components/Footer/footer.tsx
  src/components/Gnb/SearchBar.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
  src/components/SearchPage/searchPage.tsx
  src/hooks/useColorByRate.ts
  src/lib/utils/useMediaQuery.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/recoil/atoms/searchAtom.ts
  src/types/Notice.d.ts
  src/types/Shop.d.ts
  tailwind.config.ts
Labels: :sparkles: FEATURE

#35 ♻️refactor: login signup page 리팩토링
  package-lock.json
  package.json
  src/components/Gnb/Gnb.tsx
  src/components/Gnb/GnbButton.tsx
  src/components/LoginSignUp/LoginSignUp.tsx
  src/components/LoginSignUp/SignInForm.tsx
  src/components/LoginSignUp/SignUpForm.tsx
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/pages/logout.tsx
  src/recoil/atoms/AuthAtom.ts
Labels: :recycle: REFACTOR

#37 ♻️refactor: page/ShopDetail Link 연결 및 함수추가
  src/components/ShopDetail/NoticesCardList.tsx
  src/lib/utils/RemovePrefix.ts
Labels: :recycle: REFACTOR

#42 refactor: NoData 공용 컴포넌트 수정
  src/components/ShopDetail/NoData.tsx
  src/components/ShopDetail/ShopHeader/ShopHeaderSection.tsx
  src/components/ShopDetail/ShopNoData.tsx
Labels: :recycle: REFACTOR

#43 🐛fix: 메인 branch 정리 및 전역 데이터 타입 설정
  src/components/Badge/FilterBadge.tsx
  src/components/Badge/RateBadge.tsx
  src/components/Badge/StatusBadge.tsx
  src/components/Button/Button.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Filter/Filter.tsx
  src/components/Footer/footer.tsx
  src/components/Gnb/GnbButton.tsx
  src/components/Gnb/NotificationButton.tsx
  src/components/Gnb/SearchBar.tsx
  src/components/Input/InputImage.tsx
  src/components/Input/InputPassword.tsx
  src/components/Input/InputText.tsx
  src/components/LoginSignUp/InputComponent.tsx
  src/components/LoginSignUp/MemberTypeButton.tsx
  src/components/LoginSignUp/MemberTypeToggle.tsx
  src/components/LoginSignUp/SignInForm.tsx
  src/components/LoginSignUp/SignUpForm.tsx
  src/components/Modal/ModalPrimary.tsx
  src/components/NotificationModal/AlertItem.tsx
  src/components/NotificationModal/NotificationModal.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Popup/PopupsWrapper.tsx
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
  src/components/ShopDetail/NoData.tsx
  src/components/ShopDetail/NoticesCardList.tsx
  src/components/ShopDetail/NoticesList.tsx
  src/components/ShopDetail/ShopHeader/HeaderInfo.tsx
  src/components/ShopDetail/ShopHeader/ShopHeader.tsx
  src/components/ShopDetail/ShopHeader/ShopHeaderSection.tsx
  src/components/ShopDetail/ShopNoData.tsx
  src/components/Table/EmployeeTable.tsx
  src/components/Table/EmployerTable.tsx
  src/constants/DataLocations.ts
  src/constants/statusMap.ts
  src/lib/api/ApiError.ts
  src/lib/api/alertAPI.ts
  src/lib/api/applicationAPI.ts
  src/lib/api/authenticationAPI.ts
  src/lib/api/axiosInstance.ts
  src/lib/api/imageAPI.ts
  src/lib/api/noticeAPI.ts
  src/lib/api/shopAPI.ts
  src/lib/api/userAPI.ts
  src/lib/utils/Icons.tsx
  src/lib/utils/validation.ts
  src/pages/404.tsx
  src/pages/index.tsx
  src/pages/shops/[shop_id]/index.tsx
  src/pages/shops/[shop_id]/notices/index.tsx
  src/styles/globals.css
  src/types/Link.d.ts
  src/types/Notice.d.ts
  src/types/NotificationModal.ts
  src/types/Shop.d.ts
  src/types/Shop.ts
  src/types/ShopDetail.ts
  src/types/ShopOption.ts
  src/types/User.d.ts
Labels: :bug: FIX

#39 ♻️ refactor: gnb API연결 및 로직
  src/components/Footer/footer.tsx
  src/components/Gnb/Gnb.tsx
  src/components/Gnb/GnbButton.tsx
  src/components/Gnb/NotificationButton.tsx
  src/components/Gnb/SearchBar.tsx
  src/pages/_app.tsx
Labels: :recycle: REFACTOR

#45 refactor: component/filter 적용하기 버튼 및 이것저것 수정
  src/components/Filter/Filter.tsx
  src/components/Filter/LocationSection.tsx
  src/components/Gnb/GnbButton.tsx
  src/components/Gnb/NotificationButton.tsx
  src/components/pageComponents/SearchPage/searchPage.tsx
  src/components/pageComponents/ShopDetail/NoticesList.tsx
  src/components/pageComponents/ShopDetail/ShopHeader/ShopHeaderSection.tsx
  src/components/pageComponents/ShopDetail/ShopNoData.tsx
  src/lib/api/noticeAPI.ts
  src/pages/index.tsx
  src/types/ShopOption.ts
Labels: :recycle: REFACTOR

#30 ✨feat: notice detail page(공고상세페이지, 1차)
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
  src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCardButton.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailModals.tsx
  src/components/pageComponents/NoticeDetail/RecentNoticeListSection.tsx
  src/components/pageComponents/NoticeDetail/index.tsx
  src/hooks/useRecentWatchedNotices.ts
  src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
Labels: :sparkles: FEATURE

#46 refactor: 테이블컴포넌트에 뱃지와 버튼 추가
  src/components/Table/ActionButton.tsx
  src/components/Table/EmployeeTable.tsx
  src/components/Table/EmployerTable.tsx
  src/lib/api/applicationAPI.ts
  tailwind.config.ts
Labels: :recycle: REFACTOR
