Repository sprint6-team12/arbaba-40owners, pull requests merged in 2024-07, with the labels that each got.

#50 fix: EmployerTable 데이터 수정, 컴포넌트 분리
  src/components/Table/EmployerTable.tsx
  src/components/Table/EmployerTableBody.tsx
  src/components/Table/EmployerTableHeader.tsx
Labels: :bug: FIX

#57 ♻️refactor: loginSignup 리팩토링
  src/components/pageComponents/LoginSignUp/LoginSignUp.tsx
  src/components/pageComponents/LoginSignUp/MemberTypeToggle.tsx
  src/components/pageComponents/LoginSignUp/SignInForm.tsx
  src/components/pageComponents/LoginSignUp/SignInFormContainer.tsx
  src/components/pageComponents/LoginSignUp/SignUpFormContainer.tsx
Labels: :recycle: REFACTOR

#58 🐛fix: Filter 로직 변경
  src/components/Filter/DateSection.tsx
  src/components/Filter/Filter.tsx
Labels: :bug: FIX

#59 🐛fix: shopDetail 가게 정보 페이지 로직 수정
  src/pages/shops/[shop_id]/index.tsx
Labels: :bug: FIX

#60 feat: 필터컴포넌트의 기능 메인페이지 연결 (#66)
  src/pages/index.tsx
Labels: :sparkles: FEATURE

#54 ✨feat: DD-59-Main-Page-Custom-Dropdown
  public/images/icon-arrow-sort-dropdown.svg
  src/components/SortDropdown/DropdownBackdrop.tsx
  src/components/SortDropdown/DropdownButton.tsx
  src/components/SortDropdown/DropdownOptions.tsx
  src/components/SortDropdown/SortDropdown.tsx
  src/constants/sortOptionMap.ts
  src/lib/utils/Icons.tsx
  src/pages/index.tsx
Labels: :sparkles: FEATURE

#48 ✨feat: 공고상세페이지 로직 추가
  src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCardButton.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailListSection.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailSection.tsx
  src/components/pageComponents/NoticeDetail/RecentNoticeList.tsx
  src/components/pageComponents/NoticeDetail/index.tsx
  src/hooks/useApiLinksData.ts
  src/lib/api/applicationAPI.ts
  src/lib/api/noticeAPI.ts
  src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
  src/types/Application.d.ts
  src/types/Notice.d.ts
  src/types/Shop.d.ts
  src/types/User.d.ts
Labels: :sparkles: FEATURE

#53 ✨ feat: Dd 32 my page (내 프로필 페이지)
  public/images/icon-phone.svg
  src/components/Dropdown/Dropdown.tsx
  src/components/Gnb/GnbButton.tsx
  src/components/Gnb/NotificationButton.tsx
  src/components/Table/EmployeeTable.tsx
  src/components/pageComponents/AddNotice/AddNoticeInput.tsx
  src/components/pageComponents/MyPage/ConfirmModal.tsx
  src/components/pageComponents/MyPage/MyPageInput.tsx
  src/components/pageComponents/MyPage/MyPageProfile.tsx
  src/components/pageComponents/MyPage/MyPageRegistered.tsx
  src/components/pageComponents/MyPage/MyPageUnregistered.tsx
  src/components/pageComponents/NoticeDetail/RecentNoticeList.tsx
  src/components/pageComponents/ShopDetail/NoticesList.tsx
  src/constants/errorMessage.ts
  src/lib/api/noticeAPI.ts
  src/lib/api/userAPI.ts
  src/lib/utils/FormUtils.ts
  src/lib/utils/Icons.tsx
  src/lib/utils/InputValidation.ts
  src/pages/shops/[shop_id]/notices/index.tsx
  src/pages/users/[user_id]/editProfile.tsx
  src/pages/users/[user_id]/index.tsx
Labels: :sparkles: FEATURE

#62 🐛fix: disable, able 변경
  src/components/Button/Button.tsx
Labels: :bug: FIX

#63 ✨feat: 모달 백그라운드 클릭시 자동 닫힘 기능추가
  src/components/Modal/ModalCustom.tsx
  src/components/Modal/ModalPrimary.tsx
  src/components/Modal/ModalWrapper.tsx
Labels: :sparkles: FEATURE

#65 DD-76-refactor-enlarge-pagination-click-area
  src/components/Pagination/Pagination.tsx
Labels: :recycle: REFACTOR

#66 ♻️refactor: 공고상세페이지 로직 분리 및 디자인 수정
  src/components/Button/Button.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCardButton.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailModals.tsx
  src/constants/noticeDetailButtonMap.ts
  src/hooks/useApiRequestWithPopup.ts
  src/hooks/useApplicationActions.ts
  src/hooks/useNoticeDetailCardButton.ts
  tailwind.config.ts
Labels: :recycle: REFACTOR

#67 ✨feat: 공고 리스트에서 클릭해서 공고 상세로 페이지 이동 구현
  src/pages/index.tsx
Labels: :sparkles: FEATURE

#69 ♻️ refactor: my page table data 연결
  src/components/Table/EmployeeTable.tsx
  src/components/pageComponents/MyPage/MyPageProfile.tsx
  src/components/pageComponents/MyPage/MyPageRegistered.tsx
  src/constants/errorMessage.ts
  src/lib/api/applicationAPI.ts
Labels: :recycle: REFACTOR

#70 ♻️ refactor: aria-label 추가
  src/components/Badge/FilterBadge.tsx
  src/components/Badge/RateBadge.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Filter/Filter.tsx
  src/components/Footer/footer.tsx
  src/components/Gnb/GnbButton.tsx
  src/components/Gnb/SearchBar.tsx
  src/components/Input/InputImage.tsx
  src/components/Input/InputPassword.tsx
  src/components/Modal/ModalPrimary.tsx
  src/components/NotificationModal/NotificationModal.tsx
  src/components/Pagination/Pagination.tsx
  src/components/SortDropdown/SortDropdown.tsx
  src/components/pageComponents/LoginSignUp/MemberTypeButton.tsx
  src/components/pageComponents/MyPage/MyPageProfile.tsx
  src/components/pageComponents/MyPage/MyPageRegistered.tsx
  src/components/pageComponents/ShopDetail/ShopHeader/HeaderInfo.tsx
Labels: :recycle: REFACTOR

#71 ✨feat: 공고상세페이지 지원자 목록에 페이지네이션 추가 및 공고마감시 클릭제한
  src/components/Table/EmployerTable.tsx
  src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailListSection.tsx
  src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
  src/types/Application.d.ts
Labels: :sparkles: FEATURE

#73 🐛 fix : Dd 89 add shop page edit shop page css
  src/components/pageComponents/AddShopPage/index.tsx
  src/lib/utils/validation.ts
  src/pages/shops/[shop_id]/edit.tsx
Labels: :bug: FIX

#75 💄style: post card 디자인 수정
  src/components/Post/Post.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
  src/lib/utils/validation.ts
Labels: :lipstick: STYLE

#72 ♻️refactor: Dd 67 api
  src/components/Gnb/GnbButton.tsx
  src/components/pageComponents/LoginSignUp/SignInForm.tsx
  src/components/pageComponents/MyPage/MyPageInput.tsx
  src/hooks/useAuth.ts
  src/hooks/useCustomizedNotices.ts
  src/lib/api/authenticationAPI.ts
  src/lib/api/noticeAPI.ts
  src/lib/api/userAPI.ts
  src/pages/_app.tsx
  src/pages/shops/[shop_id]/index.tsx
  src/pages/users/[user_id]/index.tsx
  src/recoil/atoms/AuthAtom.ts
Labels: :recycle: REFACTOR

#74 ✨feat: 검색 기능 추가 (#74)
  package-lock.json
  package.json
  src/components/Gnb/SearchBar.tsx
  src/components/Pagination/Pagination.tsx
  src/components/pageComponents/AddShopPage/index.tsx
  src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
  src/components/pageComponents/NoticeList/NoticeListView.tsx
  src/components/pageComponents/SearchPage/SearchPage.tsx
  src/components/pageComponents/SearchPage/searchPage.tsx
  src/hooks/useNoticeList.ts
  src/lib/api/noticeAPI.ts
  src/pages/index.tsx
  src/pages/shops/[shop_id]/edit.tsx
  src/recoil/atoms/SearchResultAtom.ts
  tailwind.config.ts
Labels: :sparkles: FEATURE

#77 🐛fix: search-pagination-reset
  src/components/Gnb/SearchBar.tsx
  src/components/pageComponents/AddShopPage/index.tsx
  src/components/pageComponents/LoginSignUp/SignInForm.tsx
  src/components/pageComponents/MyPage/MyPageInput.tsx
  src/components/pageComponents/SearchPage/SearchPage.tsx
  src/constants/initialNoticeData.ts
  src/hooks/useAuth.ts
  src/hooks/useNoticeList.ts
  src/lib/api/authenticationAPI.ts
  src/pages/_app.tsx
  src/pages/users/[user_id]/index.tsx
  src/recoil/atoms/SearchResultAtom.ts
  tailwind.config.ts
Labels: :bug: FIX

#81 ✨feat: 공고상세페이지 게스트 또는 프로필 등록안했을경우 처리
  src/components/pageComponents/NoticeDetail/NoticeDetailModals.tsx
  src/hooks/useNoticeDetailCardButton.ts
Labels: :sparkles: FEATURE

#80 🐛fix: Filter 주소 여러개 검색 안되는 버그 수정
  src/lib/api/noticeAPI.ts
Labels: :bug: FIX

#84 refactor: search-improvements
  src/components/SortDropdown/DropdownBackdrop.tsx
  src/components/pageComponents/SearchPage/SearchPage.tsx
  src/hooks/useNoticeList.ts
Labels: :recycle: REFACTOR

#86 feat: 홈 이동 시 검색 초기화 기능 추가 (#103)
  src/components/Gnb/SearchBar.tsx
  src/hooks/useResetSearchOnHome.ts
  src/pages/index.tsx
Labels: :sparkles: FEATURE

#87 💄style: 팝업 fadeOut으로 사라지는 스타일 추가
  src/components/Modal/ModalPrimary.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupsWrapper.tsx
  src/hooks/usePopup.ts
  src/recoil/atoms/PopupAtom.ts
  tailwind.config.ts
Labels: :lipstick: STYLE

#79 💄style: 데스크탑일때 뱃지 디자인 변경 (제안)
  src/components/Post/PostCard.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
Labels: :lipstick: STYLE

#88 ♻️refactor: DD-105-refactor: token 인터셉터로 이동
  src/components/pageComponents/MyPage/MyPageInput.tsx
  src/hooks/useNoticeDetailCardButton.ts
  src/lib/api/alertAPI.ts
  src/lib/api/applicationAPI.ts
  src/lib/api/axiosInstance.ts
  src/lib/api/imageAPI.ts
  src/lib/api/noticeAPI.ts
  src/lib/api/shopAPI.ts
  src/lib/api/userAPI.ts
Labels: :recycle: REFACTOR

#82 ♻️refactor: 로그인 회원가입 popup, recoil 관련 수정
  src/components/Gnb/GnbButton.tsx
  src/components/pageComponents/LoginSignUp/SignInForm.tsx
  src/components/pageComponents/LoginSignUp/SignUpForm.tsx
  src/lib/api/ApiError.ts
  src/lib/api/userAPI.ts
Labels: :recycle: REFACTOR

#90 fix: 맞춤공고 데이터 없을 경우 처리
  src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
  src/hooks/useCustomizedNotices.ts
Labels: :bug: FIX

#95 ♻️refactor: 공고상세페이지 재생성 시간 변경
  src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
Labels: :recycle: REFACTOR

#96 💄style: footer , post card 디자인 수정
  src/components/Footer/footer.tsx
  src/components/Post/PostCard.tsx
  src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
Labels: :lipstick: STYLE

#97 🐛 fix: svg-error, 변수명 수정
  public/images/icon-arrow-sort-dropdown.svg
  src/components/SortDropdown/DropdownOptions.tsx
  src/components/Table/ActionButton.tsx
  src/styles/globals.css
Labels: :bug: FIX

#98 🐛fix : 페이지네이션 요소에 생키는 커서 제거, 클래스명 공백제거, 카드 호버 효과
  src/components/AddShopPage/InputComponents.tsx
  src/components/pageComponents/AddShopPage/InputComponents.tsx
  src/components/pageComponents/AddShopPage/index.tsx
  src/components/pageComponents/NoticeDetail/RecentNoticeList.tsx
  src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
  src/components/pageComponents/NoticeList/NoticeListView.tsx
  src/components/pageComponents/ShopDetail/NoticesCardList.tsx
  tailwind.config.ts
Labels: :bug: FIX

#89 💄style: LoginSignUp 모바일 디자인 변경
  src/components/Gnb/GnbButton.tsx
  src/components/pageComponents/LoginSignUp/LoginSignUp.tsx
  src/components/pageComponents/LoginSignUp/SignInForm.tsx
  src/components/pageComponents/LoginSignUp/SignInFormContainer.tsx
  src/components/pageComponents/LoginSignUp/SignUpFormContainer.tsx
  src/components/pageComponents/LoginSignUp/ToggleContainer.tsx
Labels: :lipstick: STYLE

#100 🐛fix: Dd 117 fix api reset
  next.config.mjs
  src/components/pageComponents/MyPage/MyPageInput.tsx
  src/hooks/useNoticeDetailCardButton.ts
  src/lib/api/alertAPI.ts
  src/lib/api/applicationAPI.ts
  src/lib/api/axiosInstance.ts
  src/lib/api/imageAPI.ts
  src/lib/api/noticeAPI.ts
  src/lib/api/shopAPI.ts
  src/lib/api/userAPI.ts
  src/lib/utils/FormatUtils.ts
  src/lib/utils/RemovePrefix.ts
Labels: :bug: FIX

#101 ♻️ refactor: editnotice
  src/components/pageComponents/AddNotice/EditNoticeInput.tsx
  src/pages/shops/[shop_id]/notices/[notice_id]/editNotice.tsx
Labels: :recycle: REFACTOR

#102 💄style: 포스트카드, 팝업 등 디자인 수정
  package-lock.json
  package.json
  src/components/Popup/Popup.tsx
  src/components/Post/Post.tsx
  src/components/Post/PostCard.tsx
  src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
  src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
  src/components/pageComponents/NoticeDetail/RecentNoticeList.tsx
  src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
  src/pages/_app.tsx
Labels: :lipstick: STYLE

#103 💄style: 리스트페이지 overflow 수정
  src/components/Post/Post.tsx
  src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
  src/components/pageComponents/NoticeList/NoticeListView.tsx
Labels: :lipstick: STYLE

#92 ♻️ refactor: mobile style, 파비콘, 로딩이미지
  package-lock.json
  public/arbaba.png
  public/favicon.ico
  public/images/arbaba-nothing.png
  public/images/logo.png
  public/loading-arbaba.png
  src/components/Footer/footer.tsx
  src/components/Gnb/Gnb.tsx
  src/components/pageComponents/MyPage/MyPageInput.tsx
  src/components/pageComponents/MyPage/MyPageProfile.tsx
  src/components/pageComponents/MyPage/MyPageRegistered.tsx
  src/components/pageComponents/SearchPage/SearchPage.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: :recycle: REFACTOR

#104 ♻️refactor: Dd 119 refactor shop image
  src/components/Dropdown/Dropdown.tsx
  src/components/pageComponents/AddShopPage/index.tsx
  src/components/pageComponents/MyPage/MyPageRegistered.tsx
  src/components/pageComponents/ShopDetail/NoticesCardList.tsx
  src/constants/shopOptions.ts
  src/pages/shops/[shop_id]/edit.tsx
Labels: :recycle: REFACTOR

#106 🐛fix: 지원자목록 상태변경 후 바로 업데이트 안되는 에러 수정
  src/components/Table/ActionButton.tsx
  src/components/Table/EmployerTableBody.tsx
  src/components/Table/EmployerTableItem.tsx
  src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
Labels: :bug: FIX

#107 💄style: 모바일에서 버튼 크기 수정 (overflow 이슈 해결)
  src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
  src/components/pageComponents/ShopDetail/NoData.tsx
Labels: :lipstick: STYLE

#108 📝 DOCS: DD-123-feat: 오픈 그래프 추가
  src/components/pageComponents/AddShopPage/index.tsx
  src/pages/_document.tsx
Labels: :memo: DOCS

#110 🐛fix: Dd 123 feat opengraph
  src/pages/_document.tsx
Labels: :bug: FIX, :lipstick: STYLE

#85 📝docs: readme 초안작성
  README.md
Labels: :memo: DOCS

#111 ♻️refactor: 유효성 검사 추가
  src/pages/shops/[shop_id]/index.tsx
Labels: :recycle: REFACTOR

#112 feat: 로딩 개선
  src/components/pageComponents/Loading/Loading.tsx
  src/components/pageComponents/NoticeList/NoticeListView.tsx
  src/components/pageComponents/SearchPage/SearchPage.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: :sparkles: FEATURE

#113 feat: 검색 결과 컴포넌트에서 페이지로 변경, 페이지 이동 시 검색창 값 초기화
  src/components/Gnb/SearchBar.tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: :sparkles: FEATURE
